name: mec
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.12.4
  - pynwb = 2.8.1
  - numpy = 1.26.4
  - h5py = 3.11.0
  - matplotlib = 3.8.4
  - jupyterlab = 4.2.3
  - ipywidgets = 8.1.3
  - ipytree = 0.2.2
  - pip
  - pip:
      - pynapple == 0.6.6
      - pynajax == 0.1.3
  